// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	int numberOfTimes = Integer.parseInt(args[0]);
	int smallAmount = 0;
	int bigAmount = 0;
	while(numberOfTimes > 0){
		double randomNumber = Math.random();
		if (randomNumber > 0.5){
			bigAmount += 1;
		} else 
			smallAmount += 1;
		
		numberOfTimes = numberOfTimes - 1;
	}
	if (bigAmount == 0){
		System.out.println("> 0.5: " + bigAmount);
		System.out.println("<= 0.5: " + smallAmount);
	} else {
		System.out.println("> 0.5: " + bigAmount);
		System.out.println("<= 0.5: " + smallAmount);
		System.out.println("Ratio: " + (double)smallAmount / bigAmount);
		}
	}
}
